# Initialize cmake variables

if(NOT DEFINED CMAKE_INSTALL_PREFIX)
  set(CMAKE_INSTALL_PREFIX "${CMAKE_SOURCE_DIR}/dist")
endif()

if(NOT DEFINED CMAKE_EXPORT_COMPILE_COMMANDS)
  set(CMAKE_EXPORT_COMPILE_COMMANDS YES)
endif()

set(CMAKE_CONFIGURE_FLAGS
  "-DCMAKE_INSTALL_PREFIX=\"${CMAKE_INSTALL_PREFIX}\""
  "-DCMAKE_EXPORT_COMPILE_COMMANDS=\"${CMAKE_EXPORT_COMPILE_COMMANDS}\"")
list(JOIN CMAKE_CONFIGURE_FLAGS " " CMAKE_CONFIGURE_FLAGS)
